### PR TITLE
Changed AI weight to make low CG scenarios less likely

### PR DESCRIPTION
**Pull request by ayyylmaokai**
Right now, it seems like a lot of empires are low on supplies, but are setting their trade policy to research. This should help them stay afloat. I think something else needs to be done about food.

### CODE REVIEW

**Comment by ayyylmaokai** [comment]
Also modified the way the AI chooses living standards, egalitarian AIs should never choose  a discriminatory living standard

**Comment by gebnar** [comment]
Migration limits policies either are already gone, or they will be. Auto-migration shouldn't care.

**Comment by ayyylmaokai** [comment]
The change is more to disable the automigrarion event for the player. The issue I was having is i had non citizen species moving into Gaia worlds I wanted them out of because of the automigrarion.

**Comment by gebnar** [comment]
Ahh ok. Maybe we should do like the separate mod and have planet decisions
that enable/disable migration to/from

**Pull request merged**
