### PR TITLE
Factions Overhaul, Megastructures/Terraforming SR Cost/Upkeep, Autocracy Overhaul, Localization work, Misc. Fixes

### PR DESCRIPTION
**Pull request by Vertimnus**
Localization cleanup in retile_structures_l_english.yml

### CODE REVIEW

**Comment by gebnar** [comment]
Oops... That's what I get for messing with GitHub from my phone...

Anyway, I've reviewed these, and it all looks like improvements to me! I'm in favor of merging this. I'll confirm with Metadigital first.

**Comment by Vertimnus** [comment]
> Oops... That's what I get for messing with GitHub from my phone...
> 
> Anyway, I've reviewed these, and it all looks like improvements to me! I'm in favor of merging this. I'll confirm with Metadigital first.
@gebnar 
Also just a heads up - I have very little experience with empire name modding but it looks to me like your entries in 00_empire_names for the communal parity government you added are incorrect. They reference entries in the localisation_synced folder that don't exist. Have you verified that they work?

**Comment by Metadig** [comment]
This makes too many changes to too many systems in the mod without discuss it first with the creators of the mod. I cannot approve redesigning systems without first having discussions about the flavor and mechanics of those changes.

**Comment by Vertimnus** [comment]
@Metadig Haha, you should answer your discord PMs more often then. In all seriousness though, my fault for having a mish-mash of different usernames for everything. Vertimnus = citadelacp, the person who was just discussing many of these changes with you (and some others with gebnar) on discord.

**Pull request closed without merging**
